---
title: "DPS - Cleaning & Scoring"
author: "Jan Karregat"
date: "`r Sys.Date()`"
output: html_document
---

```{r} 
Sys.setlocale("LC_MESSAGES", 'en_GB.UTF-8')
Sys.setenv(LANG = "en_US.UTF-8")

knitr::opts_chunk$set(
        echo = FALSE,
        message = FALSE,
        warning = FALSE
)

currentDate <- format(Sys.time(), "%Y-%m-%d")
FolderName <- paste("L:/DonorMedicin/FORTE/B Donor Perception Survey/B Analysis/R/3. Plots/", currentDate,sep="")
dir.create(FolderName)


library(plyr)
library(readr)
library(nFactors)
library(lavaan)
library(psych)
library(corrplot)
library(psych)
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(haven)
library(rsample)
library(broom)
library(scales)
library(kableExtra)
library(boot)
library(naniar)
library(haven)
library(foreign)
library(tidyverse)
library(tableone)
library(stargazer)
library(gridExtra)
library(cowplot)
library(broom)
library(GGally)
library(ggfortify)
library(knitr)
library(lubridate)
library(car)
library(reshape2)
library(sfsmisc)
library(MASS)
library(ordinal)
library(sjmisc)
library(VIM)
library(epiDisplay)
library(epitools)
library(ez)
library(ggbeeswarm)
library(ggthemes)
library(rsample)
library(broom)
library(scales)
library(kableExtra)
library(boot)
library(readxl)
library(foreign)
library(corrr)
library(ggcorrplot)
library(tidylog, warn.conflicts = F)
```


```{r pressure, echo=FALSE}
DPS <- readRDS("L:/DonorMedicin/FORTE/B Donor Perception Survey/B Analysis/R/2. Datasets/2. DPS - Complete Cleaned")
```


# Confirmation Factor Analysis 

```{r}
# Create matrix with data (outcome variables) for factor analysis
Factor_Data <- DPS[,c(160:168)]
Factor_Data <- Factor_Data %>% drop_na()

CFA_Model <- ' Willingness  =~ NA*IronSuppSanq1 + IronSuppSanq2 + IronSuppSanq9 
               Willingness ~~ 1*Willingness
               Invasiveness =~ NA*IronSuppSanq5 + IronSuppSanq6 + IronSuppSanq7
               Invasiveness ~~ 1*Invasiveness
               Conditions   =~ NA*IronSuppSanq3 + IronSuppSanq4 + IronSuppSanq8
               Conditions ~~ 1*Conditions '
              
fit <- lavaan::cfa(CFA_Model, data = Factor_Data)             

summary(fit, fit.measures = TRUE)

```




# Scree-plot
```{r}
ev <- eigen(cor(Factor_Data)) # get eigenvalues
ap <- parallel(subject=nrow(Factor_Data),var=ncol(Factor_Data),
  rep=100,cent=.05)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)

# Factor analysis (3 facors based on Scree-plot)
fa.none <- fa(r=Factor_Data, 
 nfactors = 3, 
 covar = FALSE, SMC = TRUE,
 fm="pa",
 max.iter=100, 
 rotate="varimax") 

### Factor analysis (3 facors based on Scree-plot)
fa.none <- fa(r=Factor_Data, 
 nfactors = 3, 
 covar = FALSE, SMC = TRUE,
 fm="pa",
 max.iter=100, 
 rotate="varimax") 

print(fa.none)

factanal.none <- factanal(Factor_Data, factors=3, scores = c("regression"), rotation = "varimax")
print(factanal.none)

FileName <- paste(FolderName, "/Factor analysis plot.png",sep="")
png(file=FileName, width = 1200, height = 480)

fa.diagram(fa.none)

dev.off()

# Rename variables
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq1"] <- "I would gladly make use of this"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq2"] <- "I would have a positive attitude towards this"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq3"] <- "I think it is important that a physician is involved "
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq4"] <- "I think it is important that my iron levels are monitored more often"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq5"] <- "This would have a negative effect on my motivation to donate"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq6"] <- "I would find this pushy"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq7"] <- "I think too much is being asked of donors"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq8"] <- "I would like to receive more information about this first"
names(Factor_Data)[names(Factor_Data) == "IronSuppSanq9"] <- "I would prefer this over postponing a next donation"

```








