---
title: "Donor Perception Survey [Regression Plots]"
author: "Jan Karregat"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Sys.setlocale("LC_MESSAGES", 'en_GB.UTF-8')
Sys.setenv(LANG = "en_US.UTF-8")
# echo "rmarkdown::render('ferritin_stats_FIN.Rmd', clean=TRUE,output_format='pdf_document',output_file='../results/ferritin_stats_FIN.pdf')" | R --slave
knitr::opts_chunk$set(
        echo = TRUE,
        message = FALSE,
        warning = FALSE
)

currentDate <- format(Sys.time(), "%Y-%m-%d")
FolderName <- paste("L:/DonorMedicin/FORTE/B Donor Perception Survey/B Analysis/R/3. Plots/", currentDate,sep="")
dir.create(FolderName)


library(plyr)
library(nFactors)
library(psych)
library(corrplot)
library(psych)
#library("ggpubr")
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(haven)
library(rsample)
library(broom)
library(scales)
library(kableExtra)
library(boot)
#library(tableone)
library(naniar)
library(haven)
library(foreign)
#library(mice)
library(tidyverse)
library(tableone)
library(stargazer)
library(gridExtra)
library(cowplot)
library(broom)
library(GGally)
library(ggfortify)
library(knitr)
library(lubridate)
library(car)
library(reshape2)
library(sfsmisc)
library(MASS)
library(ordinal)
library(sjmisc)
library(VIM)
library(epiDisplay)
library(epitools)
library(ez)
library(ggbeeswarm)
library(ggthemes)
library(rsample)
library(broom)
library(scales)
library(kableExtra)
library(boot)
library(readxl)
library(foreign)
library(corrr)
library(ggcorrplot)
library(tidylog, warn.conflicts = F)
```

# Regression dataset - Complete
```{r}
# Open Univariate dataset
Complete_Uni <- readRDS("L:/DonorMedicin/FORTE/B Donor Perception Survey/B Analysis/R/2. Datasets/4A. DPS - Linear Regression - Univariate Analysis - Complete")

# Open Multivariate dataset
Complete_Multi <- readRDS("L:/DonorMedicin/FORTE/B Donor Perception Survey/B Analysis/R/2. Datasets/5A. DPS - Linear Regression - Multivariate Analysis - Complete")

Complete_Combined <- bind_rows(Complete_Uni,Complete_Multi)
```

# Adjust dataset for plotting
```{r}
# Rename variables
Complete_Combined$Predictor <- gsub("KnowledgePolicy", "Knowledge of iron management policies", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("KnowledgeIronMetabolism", "Knowledge of iron metabolism", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("KnowledgeIronSupplements", "Knowledge of iron supplements", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("SexWomen", "Female donors", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("EducationMiddle", "College education", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("EducationHigh", "University", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("DeferralOnce", "Deferred once", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("DeferralMore than once", "Deffered more than once", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("Trust", "Trust in the blood service", Complete_Combined$Predictor)
# Complete_Combined$Predictor <- gsub("HealthGood", "Good health", Complete_Combined$Predictor)
# Complete_Combined$Predictor <- gsub("HealthVery good", "Very good health", Complete_Combined$Predictor)
# Complete_Combined$Predictor <- gsub("HealthExcellent", "Excellent health", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("DonorCareerBeginner", "Beginning donor (1-10 donations)", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("DonorCareerExperienced", "Experienced donor (>10 donations)", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("IronSuppUseYes", "Prior iron supplementation", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("AccountForIronLossAfterDonationYes", "Account for donation-related iron loss", Complete_Combined$Predictor)
Complete_Combined$Predictor <- gsub("Open_Towards_Dietary_SupplYes", "Open towards dietary supplements", Complete_Combined$Predictor)

# Generate significance column
Complete_Combined$is.sig <- !(Complete_Combined$conf.low <= 0 & 0 <= Complete_Combined$conf.high)

# Collapse columns to one
Complete_Combined$is.sig <- Complete_Combined$is.sig[, 1]
Complete_Combined$conf.low <- Complete_Combined$conf.low[, 1]
Complete_Combined$conf.high <- Complete_Combined$conf.high[, 1]


```


# Linear regression - Complete
```{r}
# Color definition 
color_mapping <- c("Knowledge of iron management policies" = "#0000FF", "Knowledge of iron metabolism" = "#0000FF", "Knowledge of iron supplements" = "#0000FF",  "Age" = "#FF6666" , "Female donors" = "#FF6666",  "College education" = "#008000",  "University" = "#008000",  "Deferred once" = "#FFA500",  "Deffered more than once" = "#FFA500",  "Trust in the blood service" = "#009999",  "Beginning donor (1-10 donations)" = "#800080",  "Experienced donor (>10 donations)" = "#800080",  "Prior iron supplementation" = "#66B2FF",    "Account for donation-related iron loss" = "#66B2FF",   "Open towards dietary supplements" = "#66B2FF")


# Predictor order
desired_order_parameter <- c("Knowledge of iron management policies", "Knowledge of iron metabolism" , "Knowledge of iron supplements", "Trust in the blood service", "Female donors", "Age", "College education", "University", "Deferred once",  "Deffered more than once",  "Beginning donor (1-10 donations)",  "Experienced donor (>10 donations)", "Prior iron supplementation", "Account for donation-related iron loss", "Open towards dietary supplements")
Complete_Combined$Predictor <- factor(Complete_Combined$Predictor, levels = rev(desired_order_parameter))

desired_order_Models <- c("Univariate", "Multivariate")
Complete_Combined$Model <- factor(Complete_Combined$Model, levels = desired_order_Models)

desired_order_Outcome <- c("Willingness", "Invasiveness", "Conditions")
Complete_Combined$Outcome <- factor(Complete_Combined$Outcome, levels = desired_order_Outcome)


orlower <- -3.5
orupper <- 3.5

# Plot
Complete_Combined_Plot <- ggplot(Complete_Combined, aes(x = estimate, y = Predictor, color = Predictor)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "solid", size = 1) +
  geom_point(aes(shape = factor(is.sig)), size = 4) +  # Convert is.sig to factor for shape mapping
  geom_linerange(aes(xmin = conf.low, xmax = conf.high), size = 1, linetype = 1) +
  scale_shape_manual(values = c(16, 1)) +  # Define shapes for TRUE and FALSE
  scale_color_manual(values = c(color_mapping)) +
  xlim(orlower, orupper) +
  theme_gray() +
  theme(
    axis.title = element_text(size = 14),
    strip.text = element_text(size = 14),
    legend.text = element_text(size = 12),
    strip.background = element_rect(fill = "white"),
    strip.background.x = element_blank(),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    panel.grid.major.y = element_line(color = "gray", linetype = "dotted"),
    panel.grid.major.x = element_blank(),
    legend.position = "none"
  ) +
  guides(shape = "none") +
  labs(title = " ") +
  xlab(" ") +
  ylab(" ") +
  facet_grid(Model ~ Outcome)

Complete_Combined_Plot


FileName <- paste(FolderName, "/Forestplots - Regression Analyses - Complete.png",sep="")
ggsave(FileName, width = 18, height = 12)

```




