---
title: "Donor iron supplement perception data summary across countries"
author: "Mikko Arvas"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    theme: united
---





```{r setup, include=FALSE}
#echo "rmarkdown::render('summarise_data_across_countries.Rmd', clean=TRUE,output_format='html_document',output_file='../results/summarise_data_across_countries.html')" | R --slave
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(readxl)
library(dplyr)

```



```{r}
currentDate <- format(Sys.time(), "%Y-%m-%d")
FolderName <- paste("L:/DonorMedicin/FORTE/E Internation Donor Perception Survey/B Analysis/R/3. Plots/", currentDate,sep="")
dir.create(FolderName)

# Read in each countries data
datafi <- readRDS("L:/DonorMedicin/FORTE/E Internation Donor Perception Survey/B Analysis/R/2. Datasets/1. iDPS - Summary data - FIN2.RDS")
datanl <- readRDS("L:/DonorMedicin/FORTE/E Internation Donor Perception Survey/B Analysis/R/2. Datasets/1. iDPS - Summary data - NL.RDS")
#datafr <- readRDS("../data/countfi.RDS")


# Create dataset with all the names 
vars_datafi <- names(datafi)
vars_datanl <- names(datanl)

# Compare common variables
common_vars <- intersect(vars_datafi, vars_datanl)

# Select common variables
datafi_common <- datafi[common_vars]
datanl_common <- datanl[common_vars]



# #filter the question metadata to what all have in common
questions_full <- read_excel("L:/DonorMedicin/FORTE/E Internation Donor Perception Survey/A Source documents/iDPS - Variable list/DPS Variable Overview.xlsx")
questions <- questions_full %>% inner_join(
  tibble(variablesfi=names(datafi_common)),
         by=c("Variable name"= "variablesfi")
         )


questions <- questions %>% inner_join(
  tibble(variablesnl=names(datanl_common)),
         by=c("Variable name"= "variablesnl")
         )




# questions <- questions %>% inner_join(
#   # [1:30] is just an example
#   tibble(variablesfr=names(datafr)[1:30]),
#          by=c("Variable name"= "variablesfr")
#          )

questions %>% select('Variable name', Values)
```



```{r}

#Extract  a vector of questions which are all answered in the same way.
q <- questions %>% filter(Category == "Preferred consequence of low iron") %>% select('Variable name') %>% unlist() %>% as.vector()

q
```



```{r}

maketable <- function(subset,country) {
  #Get the levels
#  listoflevels <- unique(lapply(datafi[q],names))
  listoflevels <- unique(lapply(subset,names))
  #some lists are shorter due to lacking values, find the longest unique set of levels
  listlength <- unlist(lapply(listoflevels,length))
  cvalues <- unlist(listoflevels[which(listlength %in% max(unlist(lapply(listoflevels,length))))])
  out <- matrix(NA, nrow = length(subset), ncol = length(cvalues))
  colnames(out) <- cvalues
  for (i in 1:length(subset)){
    iname <- names(subset)[[i]]
    for (j in cvalues) {
      out[i,j] <- subset[[iname]][j]
    }
  }
  out <- as_tibble(out)
  out$Variable <- names(subset)
  out$Country <- country
  out
}

calculate_percentages <- function(data) {
  data %>%
    group_by(Variable, Country) %>%
    mutate(percentage =round(count / sum(count) * 100,1)) %>%
    ungroup()
}

```

# Knowledge Hb

```{r}
q <- questions %>% filter(Category == "Knowledge Hb") %>% select('Variable name') %>% unlist() %>% as.vector()
qdata <- bind_rows(
  maketable(datafi[q],country="FI"), 
  maketable(datanl[q],country="NL")) %>%  
  pivot_longer(
     cols = -c(Variable,Country) ,
    names_to = "answer",
    values_to = "count"
  ) %>% 
  left_join(
    questions %>% select(Question,'Variable name'),
    by = c("Variable" = "Variable name" )
  ) %>% 
  na.omit() %>% 
  calculate_percentages() %>% 
  mutate(
    Statement = sub(".*?, then (.*)", "\\1", Question),
    Q = sub("(.*), then.*", "\\1", Question),
    answer = ordered(answer, levels=c("TRUE", "FALSE"))
  )
```

```{r}
#Faceted by answers
p <- ggplot(qdata) + 
  geom_col(aes(x=Country,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ answer, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ylab("Percentage")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=Country,y=percentage, label = percentage), vjust = -0.5, size = 3)

p

FileName <- paste(FolderName, "/Knowledge Hb - by statement.png",sep="")
ggsave(FileName, width = 8, height = 7)

```

```{r}
#Faceted by country
p <- ggplot(qdata) + 
  geom_col(aes(x=answer,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ Country, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ylab("Percentage")+
  xlab(" ")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=answer,y=percentage, label = percentage), vjust = -0.5, size = 3)+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

p

FileName <- paste(FolderName, "/Knowledge Hb - by country.png",sep="")
ggsave(FileName, width = 8, height = 7)
```

# Knowledge Ferritin

```{r}
q <- questions %>% filter(Category == "Knowledge Ferritin/iron") %>% select('Variable name') %>% unlist() %>% as.vector()
qdata <- bind_rows(
  maketable(datafi[q],country="FI"), 
  maketable(datanl[q],country="NL")) %>%  
  pivot_longer(
     cols = -c(Variable,Country) ,
    names_to = "answer",
    values_to = "count"
  ) %>% 
  left_join(
    questions %>% select(Question,'Variable name'),
    by = c("Variable" = "Variable name" )
  ) %>% 
  na.omit() %>% 
  calculate_percentages() %>% 
  mutate(
    Statement = sub(".*?, then (.*)", "\\1", Question),
    Q = sub("(.*), then.*", "\\1", Question),
    answer = ordered(answer, levels=c("TRUE", "FALSE"))
  )
```

```{r}
#Faceted by answers
p <- ggplot(qdata) + 
  geom_col(aes(x=Country,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ answer, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ylab("Percentage")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=Country,y=percentage, label = percentage), vjust = -0.5, size = 3)

p

FileName <- paste(FolderName, "/Knowledge Ferritin - by statement.png",sep="")
ggsave(FileName, width = 8, height = 7)

```
```{r}
#Faceted by country
p <- ggplot(qdata) + 
  geom_col(aes(x=answer,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ Country, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ylab("Percentage")+
  xlab(" ")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=answer,y=percentage, label = percentage), vjust = -0.5, size = 3)+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

p

FileName <- paste(FolderName, "/Knowledge Ferritin - by country.png",sep="")
ggsave(FileName, width = 8, height = 7)
```

# Perception

```{r}
q <- questions %>% filter(Category == "Perception iron supplements as policy") %>% select('Variable name') %>% unlist() %>% as.vector()
qdata <- bind_rows(
  maketable(datafi[q],country="FI"), 
  maketable(datanl[q],country="NL")) %>%  
  pivot_longer(
     cols = -c(Variable,Country) ,
    names_to = "answer",
    values_to = "count"
  ) %>% 
  left_join(
    questions %>% select(Question,'Variable name'),
    by = c("Variable" = "Variable name" )
  ) %>% 
  na.omit() %>% 
  calculate_percentages() %>% 
  mutate(
    Statement = sub(".*?, then (.*)", "\\1", Question),
    Q = sub("(.*), then.*", "\\1", Question),
    answer = ordered(answer, levels=c("Totally disagree", "Disagree", "Neutral", "Agree", "Totally agree"))
  )
```

```{r}
#Faceted by answers
p <- ggplot(qdata) + 
  geom_col(aes(x=Country,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ answer, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ggtitle(str_wrap(paste0(qdata$Q, "..."), width = 75))+
  ylab("Percentage")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=Country,y=percentage, label = percentage), vjust = -0.5, size = 3)

p

FileName <- paste(FolderName, "/Perception - by statement.png",sep="")
ggsave(FileName, width = 8, height = 7)

```

```{r}
#Faceted by country
p <- ggplot(qdata) + 
  geom_col(aes(x=answer,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ Country, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ggtitle(str_wrap(paste0(qdata$Q, "..."), width = 75))+
  ylab("Percentage")+
  xlab(" ")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=answer,y=percentage, label = percentage), vjust = -0.5, size = 3)+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

p

FileName <- paste(FolderName, "/Perception - by country.png",sep="")
ggsave(FileName, width = 8, height = 7)
```

# Preferences 

```{r}
q1 <- questions_full %>% filter(Category == "Preferred consequence of low iron") %>% select('Variable name') %>% unlist() %>% as.vector()
q2 <- questions %>% filter(Category == "Preferred consequence of low iron") %>% select('Variable name') %>% unlist() %>% as.vector()
qdata <- bind_rows(
  maketable(datafi[q1],country="FI"), 
  maketable(datanl[q2],country="NL")) %>%  
  pivot_longer(
     cols = -c(Variable,Country) ,
    names_to = "answer",
    values_to = "count"
  ) %>% 
  left_join(
    questions_full %>% select(Question,'Variable name'),
    by = c("Variable" = "Variable name" )
  ) %>% 
  na.omit() %>% 
  calculate_percentages() %>% 
  mutate(Statement = sub(".*?\\?(.*)", "\\1", Question), Q = sub("(.*?\\?.*?)\\s.*", "\\1", Question), Statement = factor(Statement, levels = c(" A longer interval between donations to replenish my iron stores.", " Dietary advice to potentially be able to donate at my regular donation interval.", " Provision of iron supplements by the blood service to be able to donate at my regular donation interval.", " Stop donating completely.", " None of these options, I prefer to keep on donating"))
)
```

```{r}
#Faceted by answers
answer.labs <- c("Male", "Female")
names(answer.labs) <- c("male", "female")

p <- ggplot(qdata) + 
  geom_col(aes(x=Country,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ answer, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ggtitle(str_wrap(paste0(qdata$Q), width = 75))+
  ylab("Percentage")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=Country,y=percentage, label = percentage), vjust = -0.5, size = 3)

p

FileName <- paste(FolderName, "/Preferences - by statement.png",sep="")
ggsave(FileName, width = 8, height = 5)
```

```{r}
#Faceted by country
p <- ggplot(qdata) + 
  geom_col(aes(x=answer,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ Country, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE)), scales = "free_x") +
  ggtitle(str_wrap(paste0(qdata$Q), width = 75))+
  ylab("Percentage")+
  xlab("Most preferred to least preferred")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=answer,y=percentage, label = percentage), vjust = -0.5, size = 3)+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

p

FileName <- paste(FolderName, "/Preferences - by country.png",sep="")
ggsave(FileName, width = 8, height = 5)
```

# Conditions 

```{r}
q <- questions %>% filter(Category == "Condition for iron supplement use") %>% select('Variable name') %>% unlist() %>% as.vector()
qdata <- bind_rows(
  maketable(datafi[q],country="FI"), 
  maketable(datanl[q],country="NL")) %>%  
  pivot_longer(
     cols = -c(Variable,Country) ,
    names_to = "answer",
    values_to = "count"
  ) %>% 
  left_join(
    questions %>% select(Question,'Variable name'),
    by = c("Variable" = "Variable name" )
  ) %>% 
  na.omit() %>% 
  calculate_percentages() %>% 
  mutate(Statement = sub(".*?\\?(.*)", "\\1", Question), Q = sub("(.*?\\?.*?)\\s.*", "\\1", Question)
)
```

```{r}
#Faceted by answers
#answer.labs <- c("Male", "Female")
#names(answer.labs) <- c("male", "female")

p <- ggplot(qdata) + 
  geom_col(aes(x=Country,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ answer, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ggtitle(str_wrap(paste0(qdata$Q), width = 75))+
  ylab("Percentage")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=Country,y=percentage, label = percentage), vjust = -0.5, size = 3)

p

FileName <- paste(FolderName, "/Conditions - by statement.png",sep="")
ggsave(FileName, width = 8, height = 5)
```

```{r}
#Faceted by country
answer.labs <- c("Male", "Female")
names(answer.labs) <- c("male", "female")

p <- ggplot(qdata) + 
  geom_col(aes(x=answer,y=percentage, fill = Country)) + 
  facet_grid(Statement ~ Country, labeller = labeller(Statement = label_wrap_gen(width=25, multi_line = TRUE))) +
  ggtitle(str_wrap(paste0(qdata$Q), width = 75))+
  ylab("Percentage")+
  xlab("")+
  scale_y_continuous(breaks = seq(0, 100, by = 50), limits = c(0, 120))+
  scale_fill_manual(values = c("FI" = "#228b22", "NL" = "#FF9B00"))+
  guides(fill = FALSE)+
  theme_bw()+
  theme(strip.text.y.right  = element_text(angle = 0))+
  geom_text(aes(x=answer,y=percentage, label = percentage), vjust = -0.5, size = 3)+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))

p

FileName <- paste(FolderName, "/Conditions - by country.png",sep="")
ggsave(FileName, width = 8, height = 5)
```